/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.b2b.service;
import cn.zhuatech.b2b.common.BusinessException; import cn.zhuatech.b2b.dto.B2bDto.*; import cn.zhuatech.b2b.model.*; import cn.zhuatech.b2b.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class B2bService {
    private final PurchaseOrderRepository orders; private final OrderActivityRecordRepository reports; private final ProductCatalogRepository productCatalog; private final FulfillmentIssueRepository fulfillmentIssues; private final CurrentUserService current;
    public B2bService(PurchaseOrderRepository orders,OrderActivityRecordRepository reports,ProductCatalogRepository productCatalog,FulfillmentIssueRepository fulfillmentIssues,CurrentUserService current){this.orders=orders;this.reports=reports;this.productCatalog=productCatalog;this.fulfillmentIssues=fulfillmentIssues;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getBusinessAccountCode();List<PurchaseOrder> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByBusinessAccountCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<PurchaseOrderView> purchaseOrders(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){PurchaseOrder order=orders.findById(id).orElseThrow(()->new BusinessException("订货单不存在"));if(order.getStatus()==PurchaseOrder.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new OrderActivityRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<PurchaseOrder> list){int planned=list.stream().mapToInt(PurchaseOrder::getPlannedQty).sum(),done=list.stream().mapToInt(PurchaseOrder::getCompletedQty).sum(),defects=list.stream().mapToInt(PurchaseOrder::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日履约",String.format("%,d",planned),list.size()+" 张订货单","blue"),new Metric("履约完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果订货运营率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("商品目录异常",productCatalog.countByStatus(ProductCatalog.Status.ALARM)+"",fulfillmentIssues.countByResult(FulfillmentIssue.Result.PENDING)+" 项待复核","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),productCatalog.findAllByOrderByCodeAsc().stream().map(e->new ControlView(e.getCode(),e.getName(),e.getBusinessAccount().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),fulfillmentIssues.findTop10ByOrderByIdDesc().stream().map(i->new FulfillmentIssueView(i.getFulfillmentIssueNo(),i.getPurchaseOrder().getOrderNo(),i.getPurchaseOrder().getProductName(),i.getFulfillmentIssueType(),i.getFulfillmentIssueQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private PurchaseOrderView view(PurchaseOrder o){return new PurchaseOrderView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getBusinessAccount().getName(),o.getBusinessAccount().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(PurchaseOrder o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
